spring.application.name=ms-ordenes-compra
server.port=8082

spring.datasource.url=jdbc:oracle:thin:@fullstack_medium?TNS_ADMIN=src/main/resources/wallet
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ADMIN
spring.datasource.password=Oracle123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.com.example.msordenes=DEBUG
